#.github/workflows/deploy-to-prod.yaml
name: Terraform PROD Deployment

on:
    push:
      branches:
        - main
    workflow_dispatch:
      branches:
        - main

permissions:
    contents: read
    issues: write

jobs:
  aws_deploy:
    runs-on: self-hosted        #      ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: Shri-kolli/VPC_EKS_TERRAFORM  
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - id: "auth"
        name: "Authenticate to AWS Cloud"
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.5.7                      #adding steps inside
      
      - name: Terraform init and validate
        working-directory: ./S3&dynamoDB
        run: | 
          terraform init 

      - name: Terraform plan
        working-directory: ./S3&dynamoDB
        run: |
          terraform plan

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Shri-kolli                             # Change Username
          minimum-approvals: 1
          issue-title: "Deploying v1.0.0 to prod"
          issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to prod."
          exclude-workflow-initiator-as-approver: false

      - name: Terraform apply
        working-directory: ./S3&dynamoDB
        run: |
          terraform apply         
                    
# come out and execute command
      - name: Terraform init and validate
        run: | 
          terraform init 

      - name: Terraform plan
        run: |
          terraform plan

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Shri-kolli                             # Change Username
          minimum-approvals: 1
          issue-title: "Deploying v1.0.0 to prod"
          issue-body: "Review the terraform plan, then approve or deny the deployment of v1.0.0 to prod."
          exclude-workflow-initiator-as-approver: false

      - name: Terraform apply
        run: |
          terraform apply
